{
    "name": "Karage POS",
    "summary": "Integrate Karage POS with Odoo",
    "version": "1.0.0",
    "development_status": "Alpha",
    "category": "Sales",
    "website": "https://karage.co",
    "author": "Karage",
    "maintainers": ["mabumusa1"],
    "license": "AGPL-3",
    "summary": "REST API endpoints for syncing orders from Karage to Odoo",
    "description": "REST API endpoints for syncing orders from Karage to Odoo",
    "depends": [
        "base",
        "product",
        "purchase",
        "point_of_sale",
        "account",
        "stock",
    ],
    "data": ["security/ir.model.access.csv", "views/external_order_sync_views.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "LGPL-3",
}
